# Generated by Django 6.0.1 on 2026-03-10 19:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgresTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(350)])),
                ('chest', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('shoulders', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('waist', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('biceps', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('neck', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('butt', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('tight', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('calf', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('picture', models.ImageField(blank=True, max_length=500, null=True, upload_to='progres_images/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_tracking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
