# Generated by Django 6.0.1 on 2026-02-07 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgresTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thur', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(350)])),
                ('chest', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('shoulders', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('waist', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('biceps', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('neck', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('butt', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('tight', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('calf', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('picture', models.ImageField(blank=True, max_length=500, null=True, upload_to='progres_images/')),
            ],
        ),
    ]
