# Generated by Django 6.0.1 on 2026-02-14 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_alter_progrestracking_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progrestracking',
            options={'ordering': ['-date']},
        ),
    ]
