# Generated by Django 6.0.3 on 2026-06-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('bg', 'Bulgarian'), ('ru', 'Russian')], default='en', max_length=2),
        ),
    ]
