# Generated by Django 6.0.3 on 2026-06-16 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_starting_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='starting_weight',
        ),
    ]
