# Generated by Django 6.0.3 on 2026-06-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_starting_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='starting_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
