# Generated by Django 6.0.1 on 2026-02-07 14:21

from django.db import migrations

def forwards_func(apps, schema_editor):
    FoodDatabase = apps.get_model("nutrition", "FoodDatabase")
    foods = [
        {"name": "Apple", "calories": 52, "protein": 0.3, "carbohydrates": 14, "fat": 0.2},
        {"name": "Banana", "calories": 89, "protein": 1.1, "carbohydrates": 23, "fat": 0.3},
        {"name": "Avocado", "calories": 160, "protein": 2, "carbohydrates": 8.5, "fat": 15},
        {"name": "Carrot (raw)", "calories": 40.2, "protein": 0.63, "carbohydrates": 7.33, "fat": 0.3},
        {"name": "Broccoli (raw)", "calories": 34, "protein": 2.82, "carbohydrates": 6.64, "fat": 0.37},
        {"name": "Potato (boiled)", "calories": 35, "protein": 0.8, "carbohydrates": 8.2, "fat": 0.2},
        {"name": "Spinach (raw)", "calories": 23, "protein": 2.9, "carbohydrates": 3.6, "fat": 0.4},
        {"name": "White Bread", "calories": 265, "protein": 9, "carbohydrates": 49, "fat": 3.2},
        {"name": "Brown Rice (cooked)", "calories": 112, "protein": 2.3, "carbohydrates": 24, "fat": 0.83},
        {"name": "Pasta (cooked)", "calories": 158, "protein": 5.8, "carbohydrates": 30.9, "fat": 0.9},
        {"name": "Oats (dry)", "calories": 379, "protein": 13.15, "carbohydrates": 67.7, "fat": 6.52},
        {"name": "Whole Milk", "calories": 100, "protein": 3.2, "carbohydrates": 4.8, "fat": 3.3},
        {"name": "Egg (boiled)", "calories": 142, "protein": 12.2, "carbohydrates": 1.4, "fat": 9.9},
        {"name": "Chicken Breast (cooked)", "calories": 219, "protein": 25, "carbohydrates": 0, "fat": 13},
        {"name": "Beef (cooked)", "calories": 250, "protein": 26, "carbohydrates": 0, "fat": 15},
        {"name": "Salmon (cooked)", "calories": 206, "protein": 22, "carbohydrates": 0, "fat": 12},
        {"name": "Lentils (cooked)", "calories": 114, "protein": 9, "carbohydrates": 20, "fat": 0.4},
        {"name": "Chickpeas (cooked)", "calories": 164, "protein": 8.9, "carbohydrates": 27, "fat": 2.6},
        {"name": "Almonds", "calories": 576, "protein": 21, "carbohydrates": 22, "fat": 49},
        {"name": "Walnuts", "calories": 654, "protein": 15, "carbohydrates": 14, "fat": 65},
        {"name": "Butter", "calories": 717, "protein": 0.9, "carbohydrates": 0.1, "fat": 81},
        {"name": "Olive Oil", "calories": 884, "protein": 0, "carbohydrates": 0, "fat": 100},
        {"name": "Cheddar Cheese", "calories": 402, "protein": 25, "carbohydrates": 1.3, "fat": 33},
        {"name": "Yogurt (plain, low-fat)", "calories": 61, "protein": 3.5, "carbohydrates": 4.7, "fat": 3.3},
        {"name": "Orange", "calories": 47, "protein": 0.94, "carbohydrates": 11.75, "fat": 0.12},
    ]
    FoodDatabase.objects.bulk_create([FoodDatabase(**food) for food in foods])

def reverse_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]

