# Generated by Django 6.0.1 on 2026-03-17 09:39

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddatabase',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Snack', 'Snack'), ('Pre Workout', 'Pre Workout'), ('Post Workout', 'Post Workout'), ('Dinner', 'Dinner')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mealfooditem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='nutritionday',
            name='name',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='nutritionday',
            unique_together={('owner', 'name')},
        ),
        migrations.AddIndex(
            model_name='fooddatabase',
            index=models.Index(fields=['name'], name='nutrition_f_name_0a4bfb_idx'),
        ),
    ]
