# Generated by Django 6.0.1 on 2026-02-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_auto_20260207_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealfooditem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
