# Generated by Django 6.0.3 on 2026-06-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_nutritiontarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealcompletion',
            name='status_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
