# Generated by Django 6.0.1 on 2026-02-14 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0004_alter_meal_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='food_items',
        ),
    ]
