# Generated by Django 6.0.1 on 2026-02-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0005_remove_meal_food_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealfooditem',
            name='measure',
            field=models.CharField(choices=[('KG', 'Kilograms'), ('P', 'Pieces'), ('ML', 'Milliliters')], max_length=50),
        ),
    ]
