# Generated by Django 6.0.1 on 2026-02-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0006_alter_mealfooditem_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Snack', 'Snack'), ('Pre workout', 'Pre workout'), ('Post workout', 'Post workout'), ('Dinner', 'Dinner')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mealfooditem',
            name='measure',
            field=models.CharField(choices=[('Kg.', 'Kilograms'), ('Pcs.', 'Pieces'), ('Ltr.', 'Liters')], max_length=50),
        ),
    ]
