# Generated by Django 6.0.1 on 2026-02-18 15:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0007_alter_meal_name_alter_mealfooditem_measure'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=50, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='meal',
            name='order',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Breakfast'), (2, 'Snack'), (3, 'Pre Workout'), (4, 'Post Workout'), (5, 'Dinner')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fooddatabase',
            name='calories',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='fooddatabase',
            name='carbohydrates',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='fooddatabase',
            name='fat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='fooddatabase',
            name='protein',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='meal',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='nutrition.nutritionday'),
        ),
    ]
