# Generated by Django 6.0.1 on 2026-02-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0007_alter_meal_name_alter_mealfooditem_measure'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=50)),
                ('meals', models.ManyToManyField(related_name='nutrition_days', to='nutrition.meal')),
            ],
        ),
    ]
