# Generated by Django 6.0.1 on 2026-02-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0009_alter_meal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Snack', 'Snack'), ('Pre workout', 'Pre workout'), ('Post workout', 'Post workout'), ('Dinner', 'Dinner')], max_length=50),
        ),
    ]
