# Generated by Django 6.0.1 on 2026-02-19 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0010_alter_meal_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fooddatabase',
            options={'ordering': ['name']},
        ),
    ]
