# Generated by Django 6.0.1 on 2026-02-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0011_alter_fooddatabase_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealfooditem',
            name='measure',
            field=models.CharField(choices=[('Gr.', 'Grams'), ('Pcs.', 'Pieces'), ('Ml.', 'Milliliters')], max_length=50),
        ),
    ]
