# Generated by Django 6.0.3 on 2026-03-17 15:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('sets', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('repetitions', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('video_link', models.URLField()),
                ('muscles', models.ManyToManyField(related_name='exercises', to='training.muscle')),
            ],
        ),
        migrations.AddField(
            model_name='muscle',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muscles', to='training.musclegroup'),
        ),
        migrations.CreateModel(
            name='TrainingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=15)),
                ('description', models.CharField(max_length=300)),
                ('exercises', models.ManyToManyField(blank=True, related_name='training_days', to='training.exercise')),
                ('muscle_groups', models.ManyToManyField(related_name='training_days', to='training.musclegroup')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['owner', 'day'],
            },
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['name'], name='training_ex_name_20b531_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingday',
            index=models.Index(fields=['owner', 'day'], name='training_tr_owner_i_cc7c61_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingday',
            index=models.Index(fields=['owner'], name='training_tr_owner_i_d4496f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trainingday',
            unique_together={('owner', 'day')},
        ),
    ]
