# Generated by Django 6.0.1 on 2026-02-07 14:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MuscleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('group_of_muscles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belongs_muscle_types', to='training.musclegroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('sets', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('repetitions', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('video_link', models.URLField()),
                ('muscles_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trained_muscle_group', to='training.musclegroup')),
                ('secondary_muscles', models.ManyToManyField(blank=True, related_name='trained_other_muscles', to='training.muscletype')),
                ('type_of_muscle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trained_muscle', to='training.muscletype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrainingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thur', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=15)),
                ('description', models.CharField(max_length=100)),
                ('exercises', models.ManyToManyField(related_name='training_exercise', to='training.exercise')),
                ('training_muscles', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muscles_trained', to='training.muscletype')),
            ],
        ),
    ]
