# Generated by Django 6.0.3 on 2026-06-19 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingDayExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_sets', models.PositiveSmallIntegerField()),
                ('custom_repetitions', models.PositiveSmallIntegerField()),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_day_exercises', to='training.exercise')),
                ('training_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_day_exercises', to='training.trainingday')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('training_day', 'exercise')},
            },
        ),
    ]
