# Generated by Django 6.0.1 on 2026-02-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingday',
            name='training_muscles',
        ),
        migrations.AddField(
            model_name='trainingday',
            name='training_muscles',
            field=models.ManyToManyField(blank=True, null=True, related_name='muscles_trained', to='training.muscletype'),
        ),
    ]
