# Generated by Django 6.0.3 on 2026-06-19 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_trainingdayexercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingday',
            name='exercises',
        ),
    ]
