# Generated by Django 6.0.1 on 2026-03-17 09:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_alter_trainingday_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingday',
            options={'ordering': ['owner', 'day']},
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='muscle',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='musclegroup',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['name'], name='training_ex_name_20b531_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingday',
            index=models.Index(fields=['owner', 'day'], name='training_tr_owner_i_cc7c61_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingday',
            index=models.Index(fields=['owner'], name='training_tr_owner_i_d4496f_idx'),
        ),
    ]
