# Generated by Django 6.0.1 on 2026-02-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_remove_trainingday_training_muscles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingday',
            name='training_muscles',
            field=models.ManyToManyField(related_name='muscles_trained', to='training.muscletype'),
        ),
    ]
