# Generated by Django 6.0.1 on 2026-02-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_alter_trainingday_training_muscles'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='split',
            field=models.ManyToManyField(related_name='exercise_split', to='training.trainingday'),
        ),
        migrations.AlterField(
            model_name='trainingday',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=15),
        ),
    ]
