# Generated by Django 6.0.1 on 2026-02-10 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_exercise_split_alter_trainingday_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='split',
        ),
        migrations.AddField(
            model_name='exercise',
            name='split',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_split', to='training.trainingday'),
        ),
    ]
