# Generated by Django 6.0.1 on 2026-02-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_remove_exercise_split_exercise_split'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingday',
            name='muscle_group',
            field=models.ManyToManyField(related_name='training_muscle_group', to='training.musclegroup'),
        ),
    ]
