# Generated by Django 6.0.3 on 2026-06-20 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_weightentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeightEntry',
        ),
    ]
