# Generated by Django 6.0.3 on 2026-06-22 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_delete_weightentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('repetitions', models.PositiveSmallIntegerField()),
                ('achieved_at', models.DateTimeField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_records', to='training.exercise')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_records', to=settings.AUTH_USER_MODEL)),
                ('workout_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_records', to='training.workoutset')),
            ],
            options={
                'indexes': [models.Index(fields=['owner', 'exercise'], name='training_pe_owner_i_1141bd_idx')],
                'unique_together': {('owner', 'exercise')},
            },
        ),
    ]
