# Generated by Django 6.0.3 on 2026-06-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_personalrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='started', max_length=20),
        ),
    ]
