# Generated by Django 6.0.3 on 2026-06-23 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_workoutsession_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutsession',
            name='is_completed',
        ),
    ]
