# Generated by Django 6.0.3 on 2026-09-23 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_remove_workoutsession_is_completed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkoutExerciseSession',
            new_name='WorkoutSessionExercise',
        ),
    ]
